services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - STORAGE_TYPE=local
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend