version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - frontend 
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development